### ISSUE TITLE
Count H+2 as headpin and S+2 as split

### ISSUE THREAD

**Issue by jbrains** [joseph-roque/bowling-companion#130]
I would at least like the option of counting H2 (headpin plus 2) as a headpin and split-plus-the-opposite-2-pin as a split. We get a lot of kicks in my home house and I'm seeing a much lower headpin % than I know I have. :)

**Comment by joseph-roque** [comment]
Hey, this is good idea, definitely an option that I'll include in the next release.

**Comment by jbrains** [comment]
On Wed, May 25, 2016 at 1:48 AM, Joseph Roque <notifications@github.com>
wrote:

> Hey, this is good idea, definitely an option that I'll include in the next
> release.
>
Marvelous. If I can get around to it, I’ll put together a pull request.
-- 
J. B. (Joe) Rainsberger :: http://online-training.jbrains.ca ::
http://www.jbrains.ca ::
http://blog.thecodewhisperer.com
